### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by sideshow** [virtualshield/rails-graphql#30]
New M2 Macbook
New Rails 7 project
Ruby 3.1.0
Developer tools intstalled

`bundle add rails-graphql` doesnt install

```
Installing rails-graphql 0.2.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rails-graphql-0.2.1/ext
/Users/adam/.rbenv/versions/3.1.0/bin/ruby -I /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0 -r ./siteconf20230823-64410-wwp3yr.rb extconf.rb
creating extconf.h
creating Makefile

current directory: /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rails-graphql-0.2.1/ext
make DESTDIR\= clean

current directory: /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rails-graphql-0.2.1/ext
make DESTDIR\=
compiling ./graphqlparser/Ast.cpp
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1709:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__debug:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:42:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1709:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__debug:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:528:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:841:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/copy.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/unwrap_iter.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/iterator_traits.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/incrementable_traits.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/concepts:156:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:841:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/copy.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/unwrap_range.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/next.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/advance.h:22:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/limits:119:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:848:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/allocator.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/new:94:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/exception:86:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:848:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/allocator.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/new:96:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:848:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/allocator.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/stdexcept:48:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:100:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:853:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/compressed_pair.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/tuple:220:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:853:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/compressed_pair.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/tuple:227:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:244:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:853:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/compressed_pair.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/tuple:227:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:251:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/compare:145:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/compare_partial_order_fallback.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/partial_order.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/weak_order.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/strong_order.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:311:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:853:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/compressed_pair.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/tuple:227:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:251:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/compare:157:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:860:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/shared_ptr.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/atomic:523:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__chrono/duration.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/ratio:85:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:860:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/shared_ptr.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/atomic:531:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:874:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:877:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:684:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/common_iterator.h:22:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/variant:220:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1712:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:877:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:725:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1714:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:41:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1851:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/ranges_sample.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/sample.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__random/uniform_int_distribution.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/bit:72:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
In file included from ./graphqlparser/Ast.cpp:8:
In file included from ./graphqlparser/Ast.h:9:
In file included from ./graphqlparser/AstNode.h:10:
In file included from ./graphqlparser/parsergen/location.hh:41:
In file included from ./graphqlparser/parsergen/position.hh:42:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:38:
./graphqlparser/version:1:1: error: expected unqualified-id
0.7.0
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Ast.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rails-graphql-0.2.1 for inspection.
Results logged to /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/extensions/arm64-darwin-22/3.1.0/rails-graphql-0.2.1/gem_make.out

  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:44:in `block in make'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:36:in `each'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:36:in `make'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/installer.rb:847:in `build_extensions'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/source/rubygems.rb:201:in `install'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/worker.rb:62:in `apply_func'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/worker.rb:54:in `loop'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/worker.rb:54:in `process_queue'
  /Users/adam/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.14/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing rails-graphql (0.2.1), and Bundler cannot continue.

In Gemfile:
  rails-graphql```

**Comment by crashtech** [comment]
I saw that you tried to install the old version `0.2.1`. Can you try with [`1.0.0.rc2`](https://rubygems.org/gems/rails-graphql/versions/1.0.0.rc2)

**Comment by sideshow** [comment]
Thanks @crashtech That worked! Closing off this issue
